version: '3'
services:
  artemis:
    container_name: activemq-artemis
    image: oceanebelle/activemq-artemis
    build:
      context: .
    restart: on-failure
    volumes: 
      - ${PWD}/config:/var/lib/artemis-instance/etc
      - ${PWD}/log:/var/lib/artemis-instance/log
    ports:
      - 8161:8161
      - 61616:61616
