version: '3'
services:
  postgres:
    container_name: postgrespi
    image: oceanebelle/postgresql:12-arm32v7
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
    volumes:
      - postgrespi:/var/lib/postgresql/data
      - ${PWD}/dumps:/dumps
    ports:
      - 5432:5432
volumes:
  postgrespi:
    driver: local
