version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: "oceanebelle/zookeeper:${DOCKER_TAG}"
    build:
      context: .
    restart: on-failure    
    volumes:
      - ${PWD}/conf/zoo.cfg:/opt/apache/zookeeper/conf/zoo.cfg
      - ${PWD}/logs:/opt/apache/zookeeper/logs
    ports:
      - 2181:2181
      - 2888:2888 
      - 3888:3888 
      - 8080:8080

      