version: '3'
services:
  zookeeper:
    container_name: zookeeper-dev
    image: "oceanebelle/zookeeper:${DOCKER_TAG}"
    restart: on-failure
    environment:
      - WILDFLY_USER=admin
      - WILDLFY_PASS=admin
    volumes:
      - ${PWD}/conf:/conf
      - ${PWD}/logs:/logs
    ports:
      - 2181:2181
      - 2888:2888 
      - 3888:3888 
      - 8080:8080
