version: '3'
services:
  wildfly:
    container_name: wildfly
    image: oceanebelle/jboss-wildfly
    build:
      context: .
    restart: on-failure
    environment:
      - WILDFLY_USER=admin
      - WILDLFY_PASS=admin
    volumes:
      - ${PWD}/deployments:/opt/jboss/wildfly/standalone/deployments
      - ${PWD}/log:/opt/jboss/wildfly/standalone/log
      - ${PWD}/scripts/conf:/opt/jboss/wildfly/standalone/configuration
    ports:
      - 8080:8080
      - 9990:9990
