version: '3'
services:

  zookeeper:
    container_name: zookeeper-messaging
    image: "oceanebelle/zookeeper:${DOCKER_TAG}"
    restart: on-failure
    volumes:
      - ${PWD}/config/zookeeper/zoo.cfg:/opt/apache/zookeeper/conf/zoo.cfg      
      - ${PWD}/config/zookeeper/log4j.properties:/opt/apache/zookeeper/conf/log4j.properties
      - ${PWD}/logs/zookeeper:/opt/apache/zookeeper/logs
      - ${PWD}/.zk_data:/opt/apache/zookeeper/data
      - ${PWD}/.zk_data_log:/opt/apache/zookeeper/datalog
    ports:
      - 2181:2181
      - 2888:2888 
      - 3888:3888 
      - 8080:8080

  kafka:
    container_name: kafka-messaging
    image: "oceanebelle/kafka:${DOCKER_TAG}"    
    depends_on: 
      - zookeeper
    restart: on-failure
    volumes:
      - ${PWD}/config/kafka/server.properties:/opt/apache/kafka/config/server.properties
      - ${PWD}/config/kafka/log4j.properties:/opt/apache/kafka/config/log4j.properties
      - ${PWD}/.kafka-data:/opt/apache/kafka/kafka-data
      - ${PWD}/logs/kafka:/opt/apache/kafka/logs    
    ports:
      - 9092:9092

