name: Build and Push latest images

on:
  push:
    branches: [ master ]
    paths: 
    - '!**.svg'
    - '!**.md'

jobs:

  build-all:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [openjdk, jboss-wildfly, activemq-artemis, postgresql]

    env:
      IMAGE: ${{matrix.image}}
      IMAGE_PATH: ${{matrix.image}}
      REPOSITORY: oceanebelle/${{matrix.image}}
      IAMGE_TAG: latest

    steps:
    - uses: actions/checkout@v2

    - name: build and push ${{matrix.image}}
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
        repository: ${REPOSITORY}
        tags: ${IMAGE_TAG}
        path: ${IMAGE_PATH}
        dockerfile: ${IMAGE_PATH}/Dockerfile
        add_git_labels: false
        push: true

