name: Build and Push latest images

on:
  push:
    branches: [ master ]
    paths: 
    - '**'  
    - '!**.svg'
    - '!**.md'

  pull_request:
    branches: [ master ]
    paths: 
    - '**/workflows/**/build-all-latest-image.yml'

jobs:

  build-multi-arch-latest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [openjdk, jboss-wildfly, activemq-artemis, postgresql]

    env:
      IMAGE: ${{ matrix.image }}
      IMAGE_PATH: ${{ matrix.image }}
      REPOSITORY: oceanebelle/${{matrix.image}}
      DOCKER_USER: ${{ secrets.DOCKER_ID }}
      DOCKER_PASS: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
      DOCKER_PLATFORM: linux/amd64,linux/arm/v7
      IMAGE_TAG: latest

    steps:
    - uses: actions/checkout@v2

    - name: setup docker buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Docker Login   
      id: buildx-login   
      if: ${{ steps.buildx.outcome == 'success' }}
      run: |        
        echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin  

    - name: Run Buildx (push image) for arm32v7     
      if: ${{ steps.buildx-login.outcome == 'success' }}
      run: |        
        docker buildx build \
          --platform ${DOCKER_PLATFORM} \
          --tag ${REPOSITORY}:${IMAGE_TAG} \
          --push .
      working-directory: ./${{env.IMAGE_PATH}}        
