name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - '**.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1.1.0
    - name: Build openjdk
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
        repository: oceaenbelle/openjdk
        path: /openjdk
        dockerfile: Dockerfile
        push: false
