name: build postgresql image

on:
  pull_request:
    branches: [ master ]
    paths: 
    - 'postgresql/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build and push postgresql
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
        repository: oceanebelle/postgresql
        tags: latest
        dockerfile: postgresql/Dockerfile
        add_git_labels: false
        push: true

